// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUjk54zBft-nkZkgG8O7urAi3zQPK9PI0',
    appId: '1:763443816299:web:eee651274fcd95f5d64e2e',
    messagingSenderId: '763443816299',
    projectId: 'dyzr-proyect',
    authDomain: 'dyzr-proyect.firebaseapp.com',
    storageBucket: 'dyzr-proyect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgnM0IG4ZVxprDLYH16GrqbPYm-l36s68',
    appId: '1:763443816299:android:9ce06f14a7f4f3efd64e2e',
    messagingSenderId: '763443816299',
    projectId: 'dyzr-proyect',
    storageBucket: 'dyzr-proyect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDW7WG5voeckTX4O7UnF4YOi0PSdyjLxc',
    appId: '1:763443816299:ios:926b5a8d8d77c330d64e2e',
    messagingSenderId: '763443816299',
    projectId: 'dyzr-proyect',
    storageBucket: 'dyzr-proyect.appspot.com',
    iosClientId: '763443816299-6vr0aqs4ghrn2uddksbssqhtjfjgttpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyzrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDW7WG5voeckTX4O7UnF4YOi0PSdyjLxc',
    appId: '1:763443816299:ios:926b5a8d8d77c330d64e2e',
    messagingSenderId: '763443816299',
    projectId: 'dyzr-proyect',
    storageBucket: 'dyzr-proyect.appspot.com',
    iosClientId: '763443816299-6vr0aqs4ghrn2uddksbssqhtjfjgttpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dyzrApp',
  );
}
