// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSCECr3eK6uh0B7hhpTt9smAu22oRgGG4',
    appId: '1:605590451889:web:571f1691af6522df46d490',
    messagingSenderId: '605590451889',
    projectId: 'dyzr-541db',
    authDomain: 'dyzr-541db.firebaseapp.com',
    storageBucket: 'dyzr-541db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4TxyZCbRvc5_uZfNT6DuCKGSJrIrfpwU',
    appId: '1:605590451889:android:9991291f2d6c91b446d490',
    messagingSenderId: '605590451889',
    projectId: 'dyzr-541db',
    storageBucket: 'dyzr-541db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUeOd3GsUwppGvrJiMVYLcaD8FatxTTm4',
    appId: '1:605590451889:ios:289e6ee72a090c9246d490',
    messagingSenderId: '605590451889',
    projectId: 'dyzr-541db',
    storageBucket: 'dyzr-541db.appspot.com',
    iosClientId: '605590451889-rvbgdhvlnip739lt1njquigh7ktqd41u.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUeOd3GsUwppGvrJiMVYLcaD8FatxTTm4',
    appId: '1:605590451889:ios:289e6ee72a090c9246d490',
    messagingSenderId: '605590451889',
    projectId: 'dyzr-541db',
    storageBucket: 'dyzr-541db.appspot.com',
    iosClientId: '605590451889-rvbgdhvlnip739lt1njquigh7ktqd41u.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyClone',
  );
}
